url: "https://nettelhorstbikebus.org"
baseurl: ""
title: "Nettelhorst Bike Bus"
# calendar requires host so cloudflare can redirect in development
calendar_url: "https://nettelhorstbikebus.org/calendar.ics"
bluesky: https://bsky.app/profile/nettelhorstbikebus.org
instagram: https://instagram.com/nettelhorstbike
tracker: https://nettelhorst-bike-bus.glitch.me/
include:
  - favicon.ico
  - apple-touch-icon.png
  - apple-touch-icon-57x57.png 
  - apple-touch-icon-72x72.png 
  - apple-touch-icon-76x76.png 
  - apple-touch-icon-114x114.png
  - apple-touch-icon-120x120.png
  - apple-touch-icon-144x144.png
  - apple-touch-icon-152x152.png
  - apple-touch-icon-180x180.png
